/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;


import java.awt.Window;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import user.user_panel;

public class login2 extends javax.swing.JPanel {

       ResultSet rs =null;
       PreparedStatement pst=null;
       Connection con =null;
       public static  String user;
       public static String pass;
       public static String guest_id;
    
    
    public login2() {
        initComponents();
        con=DatabaseManager.getconnect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l_loginBtn = new javax.swing.JLabel();
        user_txt = new javax.swing.JTextField();
        pass_txt = new javax.swing.JPasswordField();
        l_label4 = new javax.swing.JLabel();
        l_label5 = new javax.swing.JLabel();
        close_btn = new javax.swing.JLabel();
        l_label2 = new javax.swing.JLabel();
        l_label3 = new javax.swing.JLabel();
        error_msg = new javax.swing.JLabel();
        bg_image = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(500, 350));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(500, 350));
        setLayout(null);

        l_loginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/Icons/btn_default.png"))); // NOI18N
        l_loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        l_loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                l_loginBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                l_loginBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                l_loginBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                l_loginBtnMouseReleased(evt);
            }
        });
        add(l_loginBtn);
        l_loginBtn.setBounds(220, 270, 85, 40);

        user_txt.setFont(new java.awt.Font("GardensC", 0, 24)); // NOI18N
        user_txt.setToolTipText("");
        user_txt.setBorder(null);
        user_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user_txtMouseClicked(evt);
            }
        });
        user_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                user_txtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                user_txtFocusLost(evt);
            }
        });
        add(user_txt);
        user_txt.setBounds(150, 120, 260, 40);

        pass_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pass_txt.setBorder(null);
        pass_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pass_txtMouseClicked(evt);
            }
        });
        pass_txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pass_txtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pass_txtFocusLost(evt);
            }
        });
        add(pass_txt);
        pass_txt.setBounds(150, 200, 260, 40);

        l_label4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/Icons/user.png"))); // NOI18N
        add(l_label4);
        l_label4.setBounds(60, 110, 70, 50);

        l_label5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/Icons/key.png"))); // NOI18N
        add(l_label5);
        l_label5.setBounds(60, 190, 70, 50);

        close_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/Icons/close_image.png"))); // NOI18N
        close_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                close_btnMousePressed(evt);
            }
        });
        add(close_btn);
        close_btn.setBounds(430, 40, 30, 40);

        l_label2.setFont(new java.awt.Font("Dekers", 0, 14)); // NOI18N
        l_label2.setText("User ID");
        add(l_label2);
        l_label2.setBounds(150, 90, 70, 30);

        l_label3.setFont(new java.awt.Font("Dekers", 0, 14)); // NOI18N
        l_label3.setText("Password");
        add(l_label3);
        l_label3.setBounds(150, 170, 90, 30);

        error_msg.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        error_msg.setForeground(new java.awt.Color(204, 0, 0));
        add(error_msg);
        error_msg.setBounds(160, 40, 240, 40);

        bg_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/bg_img/newLogin.png"))); // NOI18N
        add(bg_image);
        bg_image.setBounds(0, 0, 510, 360);
    }// </editor-fold>//GEN-END:initComponents

    private void l_loginBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_loginBtnMouseEntered
        l_loginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/Icons/btn_hover.png")));
    }//GEN-LAST:event_l_loginBtnMouseEntered

    private void l_loginBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_loginBtnMouseExited
        l_loginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/Icons/btn_default.png")));
    }//GEN-LAST:event_l_loginBtnMouseExited

    private void l_loginBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_loginBtnMousePressed
        l_loginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/Icons/btn_pressed.png")));

        
        
        try{

                       ((Window) getRootPane().getParent()).dispose();
                        
                        
                        new index().setVisible(true);

        
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(this,e);
        }

    }//GEN-LAST:event_l_loginBtnMousePressed

    private void l_loginBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l_loginBtnMouseReleased
        l_loginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/Icons/btn_hover.png")));
    }//GEN-LAST:event_l_loginBtnMouseReleased

    private void user_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_txtMouseClicked
        
    }//GEN-LAST:event_user_txtMouseClicked

    private void pass_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pass_txtMouseClicked
        pass_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(3, 201, 169)));
    }//GEN-LAST:event_pass_txtMouseClicked

    private void close_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_btnMousePressed
        System.exit(0);
    }//GEN-LAST:event_close_btnMousePressed

    private void user_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_user_txtFocusGained
       user_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(3, 201, 169)));
    }//GEN-LAST:event_user_txtFocusGained

    private void user_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_user_txtFocusLost
      user_txt.setBorder(null);
    }//GEN-LAST:event_user_txtFocusLost

    private void pass_txtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass_txtFocusGained
    pass_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(3, 201, 169)));        // TODO add your handling code here:
    }//GEN-LAST:event_pass_txtFocusGained

    private void pass_txtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass_txtFocusLost
    pass_txt.setBorder(null);
    }//GEN-LAST:event_pass_txtFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_image;
    private javax.swing.JLabel close_btn;
    private javax.swing.JLabel error_msg;
    private javax.swing.JLabel l_label2;
    private javax.swing.JLabel l_label3;
    private javax.swing.JLabel l_label4;
    private javax.swing.JLabel l_label5;
    private javax.swing.JLabel l_loginBtn;
    private javax.swing.JPasswordField pass_txt;
    private javax.swing.JTextField user_txt;
    // End of variables declaration//GEN-END:variables
}
